uicc0 = {
# imsi = "2089900007487";
# key = "fec86ba6eb707ed08905757b1bb44b8f";
# opc= "C42449363BBAD02B66D16BC975D77CC1";
# dnn= "oai";

imsi = "999700000000002";
key = "465B5CE8B199B49FAA5F0A2EE238A6BC";
opc= "E8ED289DEBA952E4283B54E88E6183CA";
dnn= "internet";

nssai_sst=1;
# nssai_sd=1;
}

position0 = {
    x = 10.0;
    y = 0.0;
    z = 6377900.0;
}

uicc1 = {
  imsi = "999700000000002";
  key = "465B5CE8B199B49FAA5F0A2EE238A6BC";
  opc= "E8ED289DEBA952E4283B54E88E6183CA";
  dnn= "internet";
  nssai_sst= 1;
}

log_config :
{
  global_log_level                      ="error";
  hw_log_level                          ="error";
  phy_log_level                         ="error";
  mac_log_level                         ="error";
  rlc_log_level                         ="error";
  pdcp_log_level                        ="error";
  rrc_log_level                         ="error";
};
